language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker-compose --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy judgegodwins/reverseproxy:latest
  - docker tag udagram-api-user judgegodwins/udagram-api-user:v1
  - docker tag udagram-api-feed judgegodwins/udagram-api-feed:v1
  - docker tag udagram-frontend:v1 judgegodwins/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push judgegodwins/reverseproxy:latest
  - docker push judgegodwins/udagram-api-user:v1
  - docker push judgegodwins/udagram-api-feed:v1
  - docker push judgegodwins/udagram-frontend:v1